server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://eampmdb.cu1ib3gisbxt.ap-south-1.rds.amazonaws.com:5432/eampmdb
    username: eampm
    password: Admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
report:
  siteTable: Site Name, Type, Capacity