package com.hummersoft.eira.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.hummersoft.eira.dto.AnnualYieldDTO;
import com.hummersoft.eira.dto.SiteEnergyDtlDTO;
import com.hummersoft.eira.dto.SiteListDTO;
import com.hummersoft.eira.dto.SiteStatDTO;
import com.hummersoft.eira.model.Site;


public interface SiteRepository extends JpaRepository<Site, Integer>{
	
	
		
		@Query(value = "select coalesce(case when SiteTypeID='1' then 'RoofTopSites' else 'UtilitySites' end) as SiteType,"
				+ " coalesce(Sum(case when SiteTypeID='1' then 1 else null end),0) as RoofTopSites, "
				+ " coalesce(Sum(case when SiteTypeID='2' then 1 else null end),0) as UtilitySites, "
				+ " coalesce(Sum(case when SiteStatus='0' then 1 else null end),0) as OfflineStatus, "
				+ " coalesce(Sum(case when SiteStatus='1' then 1 else null end),0) as ActiveStatus, "
				+ " coalesce(Sum(case when SiteStatus='2' then 1 else null end),0) as WarningStatus, "
				+ " coalesce(Sum(case when SiteStatus='3' then 1 else null end),0) as DownStatus "
				+ " from mSite as a,tSiteStatus as b where a.SiteID=b.SiteID and a.ActiveFlag=1 and b.ActiveFlag=1 and a.SiteID in (select SiteId from mSiteMap "
				+ "where UserID= :userId and ActiveFlag=1) group by siteTypeID", nativeQuery=true)
		List<SiteStatDTO> getSiteStatistics(@Param("userId") Long userId);
		
				
		@Query(value = "Select coalesce(to_char(Max(LastChecked),'DD-MM-YYYY'),' ') as ProductionOn, "
				+ "coalesce(to_char(Max(LastChecked),'DD-MM-YYYY HH24:MI'),' ') as LastChecked, "
				+ "coalesce(to_char(Max(LastDataReceived),'DD-MM-YYYY HH24:MI'),' ') as LastDataReceived, "
				+ "coalesce(to_char(Max(LastDownTime),'DD-MM-YYYY HH24:MI'),' ') as LastDownTime, "
				+ "coalesce(Sum(TotalEnergy),0) as TotalEnergy, coalesce(Sum(TodayEnergy),0)  as TodayEnergy, "
				+ "coalesce(Max(TodayHoursOn),0) as TodayHoursOn,coalesce(sum((0.00067*TodayEnergy*1000)),0) as Co2,"
				+ "coalesce(sum((0.00067*TotalEnergy*1000)),0) as TotalCo2 from(Select (Max(LastChecked)) as ProductionOn, "
				+ "Max(LastChecked) as LastChecked, Max(LastDataReceived) as LastDataReceived, Max(LastDownTime) as LastDownTime, "
				+ "coalesce(Sum(TotalEnergy),0) as TotalEnergy,   (case when TodayEnergyFlag=1 then coalesce(Sum(TodayEnergy),0)  "
				+ "else coalesce(Sum(TotalEnergy)-Sum(YesterdayTotalEnergy),0) end) as TodayEnergy, "
				+ "coalesce(Max(TodayHoursOn),0) as TodayHoursOn,coalesce(sum((0.00067*TodayEnergy*1000)),0) as Co2,"
				+ "coalesce(sum((0.00067*TotalEnergy*1000)),0) as TotalCo2 from(select e.TodayEnergyFlag,c.categorygroup,d.SiteID,"
				+ "Max(Timestamp + (330 * interval '1 minute') ) as LastChecked,Max(LastDataReceived + (330 * interval '1 minute') ) "
				+ "as LastDataReceived,(case when e.equipmentflag=1 and c.categorygroup='EM' then Sum(coalesce(TotalEnergy,0)) else  "
				+ "case when e.equipmentflag=0 and c.categorygroup='INV' then Sum(coalesce(TotalEnergy,0)) else 0 end end) as "
				+ "TotalEnergy,(case when e.TodayEnergyFlag=1 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV')  then Sum(coalesce(TodayEnergy,0)) else case "
				+ "when e.TodayEnergyFlag=0 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV') then (Sum(coalesce(TotalEnergy,0))) else 0 end end) "
				+ "as TodayEnergy,(case when e.TodayEnergyFlag=1 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV')  then Sum(coalesce(YesterdayTotalEnergy,0)) else case "
				+ "when e.TodayEnergyFlag=0 and (e.equipmentflag=1 and c.categorygroup='EM') or (e.equipmentflag=0 "
				+ "and c.categorygroup='INV') then (Sum(coalesce(YesterdayTotalEnergy,0))) else 0 end end) as YesterdayTotalEnergy,"
				+ "Max(LastDownTime + (330 * interval '1 minute') ) as LastDownTime,Max(TodayHoursOn) as TodayHoursOn "
				+ "from tdatasource d left outer join mequipment a on d.equipmentid=a.equipmentid left outer join msite e on  "
				+ "e.siteid=a.siteid left outer join mequipmenttype b on a.equipmenttypeid=b.equipmenttypeid left outer join "
				+ "mequipmentcategory c on c.categoryid=b.categoryid where d.siteid=a.siteid and d.siteid=e.siteid and "
				+ "d.activeflag=1 and e.activeflag=1 and a.activeflag=1 and e.SiteID in (Select SiteId from mSiteMap where UserID= :userId"
				+ " and ActiveFlag=1) and c.categorygroup in('INV','EM') group by d.siteid,e.TodayEnergyFlag,"
				+ "e.equipmentflag,e.todayenergyflag,c.categorygroup ) as tbl group by todayenergyflag) tbl2",nativeQuery=true)
			List<SiteEnergyDtlDTO> getSiteEnergyDetails(@Param("userId") Long userId);
		
		
		@Query(value = "Select SiteId,Sitetype,SiteCode,SiteReference,SiteName,Latitude,Longitude,Address,City,State,Country,"
				+ "PostalCode,ActiveInverterCount,InverterCount,LastChecked,TotalEnergy,TodayEnergy,LastDownTime,LastDataReceived,"
				+ "TodayHoursOn,coalesce((case when Status=-1 then 'Active' else case when Status=2 then 'Warning' else case when Status=3 then"
				+ " 'Down' else 'Offline' end end end),'Offline') as Status,InstallationCapacity,Mobile,Telephone,LocationUrl,Cod,ActiveEMCount,"
				+ "EMCount,ProductionOn,Prodflag from(Select coalesce(SiteId,0) as SiteId,coalesce((case when Sitetypeid=1 then 'Rooftop'"
				+ "else case when Sitetypeid=2 then 'Utility' end end),' ') as Sitetype,coalesce(SiteCode,' ') as SiteCode,"
				+ "coalesce(SiteReference,' ') as SiteReference,coalesce(SiteName,' ') as SiteName,coalesce(Latitude,' ') as Latitude, "
				+ "coalesce(Longitude,' ') as Longitude,coalesce(Address,' ') as Address,coalesce(City,' ') as City,coalesce(State,' ')"
				+ "as State,coalesce(Country,' ') as Country,coalesce(PostalCode,' ') as PostalCode,coalesce(Sum(ActiveInverterCount),0) "
				+ "as ActiveInverterCount,coalesce(Sum(InverterCount),0) as InverterCount,coalesce(to_char(Max(LastChecked),"
				+ "'DD-MM-YYYY HH24:MI'),' ') as LastChecked,coalesce(Sum(TotalEnergy),0) as TotalEnergy, coalesce(Sum(TodayEnergy),0)as TodayEnergy,"
				+ "coalesce(to_char(Max(LastDownTime),'DD-MM-YYYY HH24:MI'),' ') as LastDownTime,coalesce(to_char(Max(LastDataReceived),"
				+ " 'DD-MM-YYYY HH24:MI'),' ') as LastDataReceived, coalesce(Max(TodayHoursOn),0) as TodayHoursOn,"
				+ "Max(coalesce((case when Status=1 then -1 else Status end),0)) as Status,coalesce(InstallationCapacity,0) as InstallationCapacity,"
				+ "coalesce(Mobile,' ') as Mobile,coalesce(Telephone,' ') as Telephone,coalesce(LocationUrl,' ') as LocationUrl,"
				+ "coalesce(Cod,' ') as Cod,coalesce(Prodflag,0) as Prodflag,coalesce(Sum(ActiveEMCount),0) as ActiveEMCount,"
				+ "coalesce(Sum(EMCount),0) as EMCount,coalesce(to_char(Max(LastChecked),'DD-MM-YYYY'),' ') as ProductionOn,"
				+ "coalesce(sum((0.00067*TodayEnergy*1000)),0) as Co2,coalesce(sum((0.00067*TotalEnergy*1000)),0) as TotalCo2"
				+ " from(Select SiteID,SiteTypeID,SiteCode,SiteReference,SiteName,Latitude,Longitude,Address,City,State,Country,PostalCode,"
				+ "Sum(ActiveInverterCount) as ActiveInverterCount,Sum(InverterCount) as InverterCount,Sum(ActiveEMCount) as ActiveEMCount,"
				+ "Sum(EMCount) as EMCount,(Max(LastChecked)) as ProductionOn, Max(LastChecked) as LastChecked, Max(LastDataReceived) as LastDataReceived,"
				+ "Max(LastDownTime) as LastDownTime, coalesce(Sum(TotalEnergy),0) as TotalEnergy, (case when TodayEnergyFlag=1 then coalesce(Sum(TodayEnergy),0)"
				+ " else coalesce(Sum(TotalEnergy)-Sum(YesterdayTotalEnergy),0) end) as TodayEnergy, coalesce(Max(TodayHoursOn),0) as TodayHoursOn,"
				+ "coalesce(sum((0.00067*TodayEnergy*1000)),0) as Co2,coalesce(sum((0.00067*TotalEnergy*1000)),0) as TotalCo2 ,"
				+ "Max(coalesce((case when Status=1 then -1 else Status end),0)) as Status,InstallationCapacity,Mobile,Telephone,"
				+ "LocationUrl,Cod,Prodflag from(select e.sitetypeid,e.SiteCode,e.CustomerReference as SiteReference,e.sitename,"
				+ "e.Latitude,e.longitude,e.address,e.city,g.StateName as State,h.CountryName as Country,e.postalcode,"
				+ "Max(coalesce((case when d.Status=1 then -1 else Status end),0)) as Status,Count(case when d.Status=1 and  "
				+ "a.DismandalFlag=0 and c.categorygroup='INV' then 1 else null end) as ActiveInverterCount,"
				+ "Count(distinct (case when a.DismandalFlag=0 and c.categorygroup='INV' then a.EquipmentID else null end))"
				+ "as InverterCount,Count(case when d.Status=1 and  a.DismandalFlag=0 and c.categorygroup='EM' then 1 else null end) "
				+ "as ActiveEMCount,Count(distinct (case when a.DismandalFlag=0 and c.categorygroup='EM' then a.EquipmentID else "
				+ "null end)) as EMCount,e.InstallationCapacity,e.Mobile,e.Telephone,e.SiteImage as LocationUrl,"
				+ "to_char(e.Cod ,'DD-MM-YYYY') as Cod,e.Prodflag,e.TodayEnergyFlag,c.categorygroup,e.SiteID,"
				+ "Max(Timestamp + (330 * interval '1 minute') ) as LastChecked,Max(LastDataReceived + (330 * interval '1 minute')) "
				+ "as LastDataReceived,(case when e.equipmentflag=1 and c.categorygroup='EM' then Sum(coalesce(TotalEnergy,0)) "
				+ "else  case when e.equipmentflag=0 and c.categorygroup='INV' then Sum(coalesce(TotalEnergy,0)) else 0 end end) as TotalEnergy,"
				+ "(case when e.TodayEnergyFlag=1 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV')  then Sum(coalesce(TodayEnergy,0)) else "
				+ "case when e.TodayEnergyFlag=0 and (e.equipmentflag=1 and c.categorygroup='EM') "
				+ "or (e.equipmentflag=0 and c.categorygroup='INV') then (Sum(coalesce(TotalEnergy,0))) else 0 end end) as TodayEnergy,"
				+ "(case when e.TodayEnergyFlag=1 and (e.equipmentflag=1 and c.categorygroup='EM')"
				+ "or (e.equipmentflag=0 and c.categorygroup='INV')  then Sum(coalesce(YesterdayTotalEnergy,0)) else "
				+ "case when e.TodayEnergyFlag=0 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV') then (Sum(coalesce(YesterdayTotalEnergy,0))) else 0 "
				+ "end end) as YesterdayTotalEnergy,Max(LastDownTime + (330 * interval '1 minute') ) as LastDownTime,"
				+ "Max(TodayHoursOn) as TodayHoursOn from msite e left outer join mState g on e.StateID=g.StateId "
				+ "left outer join mCountry h on e.CountryID=h.CountryID left outer join tdatasource d on e.siteid=d.siteid "
				+ "and d.activeflag=1 left outer join mequipment a on d.equipmentid=a.equipmentid  and a.activeflag=1 "
				+ "left outer join   mequipmenttype b on a.equipmenttypeid=b.equipmenttypeid left outer join "
				+ "mequipmentcategory c on c.categoryid=b.categoryid and c.categorygroup in('INV','EM') where "
				+ "e.activeflag=1 and c.categorygroup in('INV','EM') and e.SiteID in (Select SiteId from mSiteMap where UserID= :userId "
				+ "and ActiveFlag=1) group by d.siteid,e.siteid,e.sitetypeid,e.sitename,e.sitecode,e.customerreference,"
				+ "e.address,e.Latitude,e.longitude,e.city,g.StateName,h.CountryName,e.PostalCode,d.Status,a.DismandalFlag,a.EquipmentID,"
				+ "e.TodayEnergyFlag,e.equipmentflag,e.todayenergyflag,c.categorygroup,e.InstallationCapacity,e.Mobile,e.Telephone,"
				+ "e.SiteImage,e.Cod,e.Prodflag) as tbl group by SiteID,SiteTypeID,SiteCode,SiteReference,SiteName,Latitude,longitude,"
				+ "address,city,State,Country,Postalcode,todayenergyflag,InstallationCapacity,Mobile,Telephone,LocationUrl,"
				+ "Cod,Prodflag) tbl2 group by SiteID,SiteTypeID,SiteCode,SiteReference,SiteName,Address,city,Latitude,"
				+ "longitude,State,Country,postalcode,InstallationCapacity,Mobile,Telephone,LocationUrl,Cod,Prodflag) tbl3 order by status",nativeQuery=true)
	          List<SiteListDTO>  getSiteList(@Param("userId") Long userId);                   
		

		@Query(value = "Select SiteID,sum(coalesce(TodayEnergy,0)) as annualyieldvalue from (Select SiteID as SiteID, SiteName, "
				+ "Timestamp, (case when TodayEnergyFlag=1 then TodayEnergy else (DailyEnergy - Lag(DailyEnergy) OVER "
				+ "( ORDER BY SiteID, Timestamp)) end) as TodayEnergy from (Select t1.SiteID as SiteID, (t3.SiteName) as SiteName, "
				+ "Timestamp, t3.TodayEnergyFlag, TotalEnergy, TodayEnergy, (coalesce(TotalEnergy, 0) - coalesce(YesterdayEnergy, 0)) "
				+ "as DailyEnergy from (Select SiteID, Timestamp, coalesce(Sum(coalesce(TotalEnergy, 0)), 0) as TotalEnergy, "
				+ "coalesce(Sum(coalesce(TodayEnergy, 0)), 0) as TodayEnergy from (Select SiteID, date_trunc('day', Timestamp) as "
				+ "Timestamp, EquipmentID, Max(coalesce(TotalEnergy, 0)) as TotalEnergy, Max(coalesce(TodayEnergy, 0)) as TodayEnergy "
				+ "from tDataTransaction where SiteID = :siteId"
				+ " and EquipmentID in (Select EquipmentId from mEquipment where ActiveFlag=1 and SiteId=:siteId"
				+ " and EquipmentTypeId in (Select EquipmentTypeId from mEquipmentType where ActiveFlag=1 and CategoryId in "
				+ "(Select CategoryId from mEquipmentCategory where ActiveFlag=1 and CategoryGroup in (case when "
				+ "(select EquipmentFlag from mSite where SiteId =:siteId"
				+ ") in (0) then 'INV' else 'EM' end)))) and date_part('year', Timestamp+ interval '1 day') = date_part('year', "
				+ "CURRENT_DATE) group by SiteID, date_trunc('day', Timestamp), EquipmentID) tbl1 group by SiteID, Timestamp) t1 "
				+ "left outer join ( Select SiteID, YesterdayEnergy from (Select SiteID, Timestamp, ROW_NUMBER() "
				+ "over( order by Timestamp desc) as Sno, coalesce(Sum(coalesce(TotalEnergy, 0)), 0) as YesterdayEnergy "
				+ "from (Select SiteID, date_trunc('day', Timestamp) as Timestamp, EquipmentID, Max(coalesce(TotalEnergy, 0)) as "
				+ "TotalEnergy, Max(coalesce(TodayEnergy, 0)) as TodayEnergy from tDataTransaction where SiteID=:siteId"
				+ " and EquipmentID in (Select EquipmentId from mEquipment where ActiveFlag=1 and SiteId=:siteId and EquipmentTypeId in "
				+ "(Select EquipmentTypeId from mEquipmentType where ActiveFlag=1 and CategoryId in (Select CategoryId from "
				+ "mEquipmentCategory where ActiveFlag=1 and CategoryGroup in (case when (select EquipmentFlag from mSite where "
				+ "SiteId = :siteId) in (0) then 'INV' else 'EM' end)))) and Timestamp < date_trunc('day',to_timestamp('01-01-' || "
				+ "date_part('year', CURRENT_DATE) || ' 00:00:00','DD/MM/YYYY HH24:MI:SS')) group by SiteID, date_trunc('day', "
				+ "Timestamp), EquipmentID) tbl1 group by SiteID, Timestamp) tbl1 where Sno=1) t2 on t2.SiteID=t1.SiteID left "
				+ "outer join mSite t3 on t3.SiteID=t1.SiteID ) tbl ) tblfinal group by SiteID", nativeQuery=true)
		List<AnnualYieldDTO> getAnnualYieldForSite(@Param("siteId") int siteId);
		
		@Query(value = "Select SiteId,Sitetype,SiteCode,SiteReference,SiteName,Latitude,Longitude,Address,City,State,Country,"
				+ "PostalCode,ActiveInverterCount,InverterCount,LastChecked,TotalEnergy,TodayEnergy,LastDownTime,LastDataReceived,"
				+ "TodayHoursOn,coalesce((case when Status=-1 then 'Active' else case when Status=2 then 'Warning' else case when Status=3 then"
				+ " 'Down' else 'Offline' end end end),'Offline') as Status,InstallationCapacity,Mobile,Telephone,LocationUrl,Cod,ActiveEMCount,"
				+ "EMCount,ProductionOn,Prodflag from(Select coalesce(SiteId,0) as SiteId,coalesce((case when Sitetypeid=1 then 'Rooftop'"
				+ "else case when Sitetypeid=2 then 'Utility' end end),' ') as Sitetype,coalesce(SiteCode,' ') as SiteCode,"
				+ "coalesce(SiteReference,' ') as SiteReference,coalesce(SiteName,' ') as SiteName,coalesce(Latitude,' ') as Latitude, "
				+ "coalesce(Longitude,' ') as Longitude,coalesce(Address,' ') as Address,coalesce(City,' ') as City,coalesce(State,' ')"
				+ "as State,coalesce(Country,' ') as Country,coalesce(PostalCode,' ') as PostalCode,coalesce(Sum(ActiveInverterCount),0) "
				+ "as ActiveInverterCount,coalesce(Sum(InverterCount),0) as InverterCount,coalesce(to_char(Max(LastChecked),"
				+ "'DD-MM-YYYY HH24:MI'),' ') as LastChecked,coalesce(Sum(TotalEnergy),0) as TotalEnergy, coalesce(Sum(TodayEnergy),0)as TodayEnergy,"
				+ "coalesce(to_char(Max(LastDownTime),'DD-MM-YYYY HH24:MI'),' ') as LastDownTime,coalesce(to_char(Max(LastDataReceived),"
				+ " 'DD-MM-YYYY HH24:MI'),' ') as LastDataReceived, coalesce(Max(TodayHoursOn),0) as TodayHoursOn,"
				+ "Max(coalesce((case when Status=1 then -1 else Status end),0)) as Status,coalesce(InstallationCapacity,0) as InstallationCapacity,"
				+ "coalesce(Mobile,' ') as Mobile,coalesce(Telephone,' ') as Telephone,coalesce(LocationUrl,' ') as LocationUrl,"
				+ "coalesce(Cod,' ') as Cod,coalesce(Prodflag,0) as Prodflag,coalesce(Sum(ActiveEMCount),0) as ActiveEMCount,"
				+ "coalesce(Sum(EMCount),0) as EMCount,coalesce(to_char(Max(LastChecked),'DD-MM-YYYY'),' ') as ProductionOn,"
				+ "coalesce(sum((0.00067*TodayEnergy*1000)),0) as Co2,coalesce(sum((0.00067*TotalEnergy*1000)),0) as TotalCo2"
				+ " from(Select SiteID,SiteTypeID,SiteCode,SiteReference,SiteName,Latitude,Longitude,Address,City,State,Country,PostalCode,"
				+ "Sum(ActiveInverterCount) as ActiveInverterCount,Sum(InverterCount) as InverterCount,Sum(ActiveEMCount) as ActiveEMCount,"
				+ "Sum(EMCount) as EMCount,(Max(LastChecked)) as ProductionOn, Max(LastChecked) as LastChecked, Max(LastDataReceived) as LastDataReceived,"
				+ "Max(LastDownTime) as LastDownTime, coalesce(Sum(TotalEnergy),0) as TotalEnergy, (case when TodayEnergyFlag=1 then coalesce(Sum(TodayEnergy),0)"
				+ " else coalesce(Sum(TotalEnergy)-Sum(YesterdayTotalEnergy),0) end) as TodayEnergy, coalesce(Max(TodayHoursOn),0) as TodayHoursOn,"
				+ "coalesce(sum((0.00067*TodayEnergy*1000)),0) as Co2,coalesce(sum((0.00067*TotalEnergy*1000)),0) as TotalCo2 ,"
				+ "Max(coalesce((case when Status=1 then -1 else Status end),0)) as Status,InstallationCapacity,Mobile,Telephone,"
				+ "LocationUrl,Cod,Prodflag from(select e.sitetypeid,e.SiteCode,e.CustomerReference as SiteReference,e.sitename,"
				+ "e.Latitude,e.longitude,e.address,e.city,g.StateName as State,h.CountryName as Country,e.postalcode,"
				+ "Max(coalesce((case when d.Status=1 then -1 else Status end),0)) as Status,Count(case when d.Status=1 and  "
				+ "a.DismandalFlag=0 and c.categorygroup='INV' then 1 else null end) as ActiveInverterCount,"
				+ "Count(distinct (case when a.DismandalFlag=0 and c.categorygroup='INV' then a.EquipmentID else null end))"
				+ "as InverterCount,Count(case when d.Status=1 and  a.DismandalFlag=0 and c.categorygroup='EM' then 1 else null end) "
				+ "as ActiveEMCount,Count(distinct (case when a.DismandalFlag=0 and c.categorygroup='EM' then a.EquipmentID else "
				+ "null end)) as EMCount,e.InstallationCapacity,e.Mobile,e.Telephone,e.SiteImage as LocationUrl,"
				+ "to_char(e.Cod ,'DD-MM-YYYY') as Cod,e.Prodflag,e.TodayEnergyFlag,c.categorygroup,e.SiteID,"
				+ "Max(Timestamp + (330 * interval '1 minute') ) as LastChecked,Max(LastDataReceived + (330 * interval '1 minute')) "
				+ "as LastDataReceived,(case when e.equipmentflag=1 and c.categorygroup='EM' then Sum(coalesce(TotalEnergy,0)) "
				+ "else  case when e.equipmentflag=0 and c.categorygroup='INV' then Sum(coalesce(TotalEnergy,0)) else 0 end end) as TotalEnergy,"
				+ "(case when e.TodayEnergyFlag=1 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV')  then Sum(coalesce(TodayEnergy,0)) else "
				+ "case when e.TodayEnergyFlag=0 and (e.equipmentflag=1 and c.categorygroup='EM') "
				+ "or (e.equipmentflag=0 and c.categorygroup='INV') then (Sum(coalesce(TotalEnergy,0))) else 0 end end) as TodayEnergy,"
				+ "(case when e.TodayEnergyFlag=1 and (e.equipmentflag=1 and c.categorygroup='EM')"
				+ "or (e.equipmentflag=0 and c.categorygroup='INV')  then Sum(coalesce(YesterdayTotalEnergy,0)) else "
				+ "case when e.TodayEnergyFlag=0 and (e.equipmentflag=1 and c.categorygroup='EM') or "
				+ "(e.equipmentflag=0 and c.categorygroup='INV') then (Sum(coalesce(YesterdayTotalEnergy,0))) else 0 "
				+ "end end) as YesterdayTotalEnergy,Max(LastDownTime + (330 * interval '1 minute') ) as LastDownTime,"
				+ "Max(TodayHoursOn) as TodayHoursOn from msite e left outer join mState g on e.StateID=g.StateId "
				+ "left outer join mCountry h on e.CountryID=h.CountryID left outer join tdatasource d on e.siteid=d.siteid "
				+ "and d.activeflag=1 left outer join mequipment a on d.equipmentid=a.equipmentid  and a.activeflag=1 "
				+ "left outer join   mequipmenttype b on a.equipmenttypeid=b.equipmenttypeid left outer join "
				+ "mequipmentcategory c on c.categoryid=b.categoryid and c.categorygroup in('INV','EM') where "
				+ "e.activeflag=1 and c.categorygroup in('INV','EM') and e.SiteID in (Select SiteId from mSiteMap where UserID= :userId "
				+ "and ActiveFlag=1) group by d.siteid,e.siteid,e.sitetypeid,e.sitename,e.sitecode,e.customerreference,"
				+ "e.address,e.Latitude,e.longitude,e.city,g.StateName,h.CountryName,e.PostalCode,d.Status,a.DismandalFlag,a.EquipmentID,"
				+ "e.TodayEnergyFlag,e.equipmentflag,e.todayenergyflag,c.categorygroup,e.InstallationCapacity,e.Mobile,e.Telephone,"
				+ "e.SiteImage,e.Cod,e.Prodflag) as tbl group by SiteID,SiteTypeID,SiteCode,SiteReference,SiteName,Latitude,longitude,"
				+ "address,city,State,Country,Postalcode,todayenergyflag,InstallationCapacity,Mobile,Telephone,LocationUrl,"
				+ "Cod,Prodflag) tbl2 group by SiteID,SiteTypeID,SiteCode,SiteReference,SiteName,Address,city,Latitude,"
				+ "longitude,State,Country,postalcode,InstallationCapacity,Mobile,Telephone,LocationUrl,Cod,Prodflag order by TodayEnergy desc) tbl3 order by TodayEnergy desc",nativeQuery=true)
	          List<SiteListDTO>  getSiteListForDashboard(@Param("userId") Long userId); 
		

}
